"""
Matplotlib and PyVista bridge to render images and GIFs 
for analytical procedural grids generated by Octave.
"""
import sys
import os
import numpy as np
import scipy.io
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.animation import FuncAnimation, PillowWriter
import pyvista as pv

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'Helvetica', 'DejaVu Sans'],
    'font.size': 14,
    'axes.spines.top': False,
    'axes.spines.right': False
})

def save_rendered_array_via_matplotlib(img_array, output_filename, title=None, dpi=300):
    fig, ax = plt.subplots(figsize=(8, 8), dpi=dpi)
    ax.imshow(img_array)
    ax.axis('off')
    if title: 
        ax.set_title(title)
    plt.savefig(output_filename, dpi=dpi, bbox_inches='tight', facecolor='white')
    plt.close(fig)

def save_image_from_mat(mat_file, output_filename, title=None, dpi=300):
    try:
        data = scipy.io.loadmat(mat_file)
    except Exception as e:
        print(f"      |-> [x] PyVista - Could not open buffer {mat_file}. Details: {e}")
        return

    if 'presence' in data:
        matrix = data['presence']
    else:
        keys = [k for k in data.keys() if not k.startswith('__')]
        if not keys:
            print("      |-> [x] PyVista - No matrix found in buffer.")
            return
        matrix = data[keys[0]]

    matrix = np.squeeze(matrix)
    matrix = (matrix > 0).astype(int)

    fibro_cmap = ListedColormap(['#1A80CC', '#E6801A']) 
    color_healthy = "#1A80CC"  
    color_fibrosis = "#E6801A" 
    ndim = matrix.ndim
    
    if ndim == 2:
        fig, ax = plt.subplots(figsize=(8, 8), dpi=dpi)
        ax.imshow(matrix, cmap=fibro_cmap, interpolation='nearest', origin='lower')
        ax.axis('off')
        if title: ax.set_title(title)
        plt.savefig(f"{output_filename}.png", dpi=dpi, bbox_inches='tight', facecolor='white')
        plt.close(fig)
        print(f"      |-> Matplotlib - 2D render saved.")

    elif ndim == 3:
        Ny, Nx, Nz = matrix.shape
        
        # 1. GIF Slice-by-Slice
        fig_gif, ax_gif = plt.subplots(figsize=(8, 8), dpi=dpi)
        if title: fig_gif.suptitle(title)
        ax_gif.axis('off')
        
        im_gif = ax_gif.imshow(matrix[:, :, 0], cmap=fibro_cmap, interpolation='nearest', origin='lower', vmin=0, vmax=1)
        title_txt = ax_gif.set_title(f"Z-Slice: 0 / {Nz-1}")
        
        def update_frame(k):
            im_gif.set_array(matrix[:, :, k])
            title_txt.set_text(f"Z-Slice: {k} / {Nz-1}")
            return im_gif, title_txt

        anim = FuncAnimation(fig_gif, update_frame, frames=Nz, interval=100, blit=False)
        try:
            anim.save(f"{output_filename}_movie.gif", writer=PillowWriter(fps=10))
            print(f"      |-> Matplotlib - 3D Cross-Sectional GIF compiled.")
        except Exception as e: 
            pass
        plt.close(fig_gif)

        # 2. Setup PyVista
        pv.set_plot_theme("document") 
        matrix_pv = np.transpose(matrix, (1, 0, 2))
        
        grid = pv.ImageData()
        grid.dimensions = np.array(matrix_pv.shape) + 1
        grid.spacing = (1, 1, 1) 
        grid.cell_data["values"] = matrix_pv.flatten(order="F") 
        
        # 3. Orthogonal Slices
        slices = grid.slice_orthogonal()
        p = pv.Plotter(off_screen=True, window_size=[1024, 1024])
        p.set_background('white')
        p.add_mesh(grid.outline(), color="k")
        p.add_mesh(slices, cmap=[color_healthy, color_fibrosis], show_scalar_bar=False, lighting=False)
        p.view_isometric()
        
        img_array_ortho = p.screenshot(return_img=True)
        p.close()
        save_rendered_array_via_matplotlib(img_array_ortho, f"{output_filename}_ortho_slices.png", title, dpi)
        print(f"      |-> PyVista - Orthogonal intersection views saved.")

        # 4. Volumetric Render 
        fibrosis_mesh = grid.threshold(0.5)
        p = pv.Plotter(off_screen=True, window_size=[1024, 1024])
        p.set_background('white')
        p.add_mesh(grid.outline(), color="k")
        p.add_mesh(fibrosis_mesh, color=color_fibrosis, smooth_shading=True, specular=0.5, diffuse=0.8, ambient=0.3)
        p.view_isometric()
        
        img_array_vol = p.screenshot(return_img=True)
        p.close()
        save_rendered_array_via_matplotlib(img_array_vol, f"{output_filename}_fibrosis_volume.png", title, dpi)
        print(f"      |-> PyVista - 3D volumetric pattern render saved.")

    try: 
        os.remove(mat_file)
    except: 
        pass

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("      |-> Usage: python save_fibrosis_image.py <input.mat> <output_name> [title]")
        exit(1)
    
    input_mat = sys.argv[1]
    output = sys.argv[2]
    ttl = sys.argv[3] if len(sys.argv) > 3 else None
    
    save_image_from_mat(input_mat, output, ttl)